version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/src/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
networks:
  default:
    driver: bridge



